SELECT
    CHILD.ID,
    CHILD.GENOTYPE,
    PARENT.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA CHILD
LEFT JOIN ECOLI_DATA PARENT ON CHILD.PARENT_ID = PARENT.ID
WHERE PARENT.GENOTYPE & CHILD.GENOTYPE = PARENT.GENOTYPE
ORDER BY CHILD.ID ASC