SELECT SUM(FC) AS FISH_COUNT
FROM(
    SELECT COUNT(FNI.FISH_NAME) AS FC
FROM FISH_INFO FI
JOIN FISH_NAME_INFO FNI ON FI.FISH_TYPE = FNI.FISH_TYPE
WHERE FNI.FISH_NAME LIKE 'BASS' OR FNI.FISH_NAME LIKE 'SNAPPER'
GROUP BY FNI.FISH_NAME
)
AS SUBQUERY